-- ==========================================
-- SCRIPT SETUP DATABASE SUPABASE (alat_camp)
-- Jalankan script ini di SQL Editor Supabase Anda
-- ==========================================

-- 1. Hapus tabel jika sudah ada (Opsional, untuk reset)
-- DROP TABLE IF EXISTS public.alat_camp;

-- 2. Membuat tabel alat_camp
CREATE TABLE IF NOT EXISTS public.alat_camp (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_alat VARCHAR(255) NOT NULL,
    harga_sewa INTEGER NOT NULL,
    stok INTEGER NOT NULL DEFAULT 0,
    gambar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Mengaktifkan Row Level Security (RLS)
ALTER TABLE public.alat_camp ENABLE ROW LEVEL SECURITY;

-- 4. Kebijakan Keamanan (RLS Policies)

-- Policy A: Siapa saja (Anonim/User Umum) bisa melihat data produk (SELECT)
CREATE POLICY "Public Read Access" 
ON public.alat_camp 
FOR SELECT 
USING (true);

-- Policy B: Hanya User yang Login (Admin) yang bisa menambah produk (INSERT)
CREATE POLICY "Admin Insert Access" 
ON public.alat_camp 
FOR INSERT 
TO authenticated 
WITH CHECK (true);

-- Policy C: Hanya User yang Login (Admin) yang bisa mengedit produk (UPDATE)
CREATE POLICY "Admin Update Access" 
ON public.alat_camp 
FOR UPDATE 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- Policy D: Hanya User yang Login (Admin) yang bisa menghapus produk (DELETE)
CREATE POLICY "Admin Delete Access" 
ON public.alat_camp 
FOR DELETE 
TO authenticated 
USING (true);

-- ==========================================
-- DATA AWAL (SEED DATA)
-- Memasukkan produk awal berdasarkan katalog statis
-- ==========================================
INSERT INTO public.alat_camp (nama_alat, harga_sewa, stok, gambar_url) VALUES
('Tenda Arei 4 Capacity', 50000, 5, 'tenda .jpg.jpeg'),
('Fly Sheet', 10000, 10, 'fly sheet .jpg.jpeg'),
('Portable Chair', 10000, 8, 'kursi 1.jpg.jpeg'),
('Kursi Set C', 25000, 4, 'kursi meja .jpg.jpeg'),
('Port. Table', 15000, 6, 'meja .lpg.jpeg'),
('Kursi Set A', 50000, 3, '4 kursi .jpg.jpeg'),
('Portables Gas', 15000, 20, 'gas portable .jpg.jpeg'),
('Tikar', 10000, 15, 'tikar .jpg.jpeg'),
('Cooking Set', 35000, 7, 'cooking set .jpg.jpeg'),
('Hammock', 10000, 12, 'hammock .jpg.jpeg'),
('Emergancy Lamp', 10000, 10, 'lampu .jpg.jpeg')
ON CONFLICT DO NOTHING;
